title: "Qizhong (George) Guo"
description: "Faculty page of Professor Qizhong (George) Guo, Civil & Environmental Engineering, Rutgers Universityâ€“New Brunswick."
theme: minima

nav_links:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "Research"
    url: /research
  - title: "Reflections"
    url: /reflections
  - title: "Teaching"
    url: /teaching
  - title: "Facilities"
    url: /facilities
  - title: "Publications"
    url: /publications
  - title: "Contact"
    url: /contact
