title: "Qizhong (George) Guo"
description: "Civil & Environmental Engineering — Rutgers University–New Brunswick."
theme: minima

header_pages:
  - index.md
  - about.md
  - research.md
  - reflections.md
  - teaching.md
  - facilities.md
  - publications/index.md
  - contact.md
