description: "Faculty page of Professor Qizhong (George) Guo, Civil & Environmental Engineering, Rutgers Universityâ€“New Brunswick."
theme: minima

header_pages:
  - index.md
  - about.md
  - research.md
  - reflections.md
  - teaching.md
  - facilities.md
  - publications/index.md
  - contact.md
